"use client"

import Link from "next/link"
import { useSupabase } from "../../../app/supabase-provider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function Header() {
  const { supabase, session } = useSupabase()

  const handleLogout = async () => {
    await supabase.auth.signOut()
  }
  return (
    <header className="flex w-screen h-20 items-center justify-between p-4 shadow mb-4">
      <Link href="/">
        <h1 className="font-bold text-lg">OurLists</h1>
      </Link>
      {session && (
        <button
          className="p-4 bg-green-100 rounded hover:bg-green-300"
          onClick={() => handleLogout()}
        >
          Logout
        </button>
      )}
    </header>
  )
}
